### ISSUE TITLE
是否要在services列表里，增加批量匹配的功能

### ISSUE THREAD

**Issue by bootun** [bootun/veronica#40]
For example, there is a gRPC struct called 'FooServer', which implements the interface of protoc-gen-grpc to generate xx.grpc.go, and there are many methods. Is it possible to support it like this:

```yaml
services:
  foo:
    endpoint: 'internal/server/grpc.go:(*FooServer).*'
```

但是这样的话，报告的时候应该如何输出呢?   

当前报告都是基于service的name机性能报告的，按当前逻辑，应该输出`foo`受到了影响
