### ISSUE TITLE
proposal: new configuration file structure

### ISSUE THREAD

**Issue by bootun** [bootun/veronica#7]
Provide finer grained control capabilities for each service

**current:**
```yaml
version: 0.0.2
project:
  # can be omitted
  go.mod: go.mod
  # your service
  entrypoint:
    - cmd/api-gateway
    - cmd/assets-manager
    - cmd/assets-cron
```

**new:**
```yaml
version: 0.1.0
services: 
  # services
  api-gateway:
    # main package
    entrypoint: cmd/api-gateway
    ignore:
      - xxx.go
    hooks:
      - a.file
  assets-manager:
    entrypoint: ./cmd/assets-manager
    ignore:
      - xxx.go
    hooks:
      - xx.file
```
